language: java
sudo: required
install: true
jdk: oraclejdk8
script: ./travis.sh
dist: trusty

branches:
  except:
  - gh-pages

cache:
  directories:
    - $HOME/.sonar
    - $HOME/tools
    - $HOME/.m2/repository

install: true
